#!/usr/bin/env python3
"""Write the POWHEG cards of the paper-plots production.

    powheg/production/make_cards.py            # write
    powheg/production/make_cards.py --check    # report what would change

PRODUCTION.md: five energies (beams.BENCH_ENERGIES) x two nucleons, for
POWHEG-RES muon NC and POWHEG-V2 neutrino CC:

    powheg/cards/production/POWHEG-RES/mu<TAG>-<t>/powheg.input
    powheg/cards/production/POWHEG-V2/nu<TAG>-<t>/powheg.input
    powheg/cards/production/POWHEG-V2mc/nu<TAG>-<t>/powheg.input   (massive charm)

The templates are the the earlier production 1 TeV production cards, READ and never written
(mu1TeV-wide, nu1TeV-prod): every physics setting -- scales, EW scheme,
massless c/b, the generation Q2 cut, the integration parameters -- carries
over unchanged, and only the beam, the nucleon and the event count change.

THE NEUTRON IS A GENUINE NEUTRON BEAM, ih2 = 2, WITH THE PROTON PDF SET.
Both codes isospin-conjugate the proton set themselves for hadron code 2:
  * POWHEG-RES  DIS_v/POWHEGpatch/lhapdf6if.f, genericpdf: `elseif(ih.eq.2)`
    swaps u <-> d and ubar <-> dbar after the LHAPDF call;
  * POWHEG-V2   POWHEG-BOX-V2/pdfcalls.f, genericpdf0: `if(abs(ih) == 2)`
    calls the proton and swaps the same four entries;
and both write idbmup(2) = 2112 into the LHE <init> line (pwhg_init.f), which
is where Pythia 8 takes its beams from.  Pythia 8.311 in turn conjugates the
PROTON PDF:pSet for a 2112 beam (PDF::xf, beamType -1), so the showered event
has a neutron beam, a neutron remnant and neutron PDFs in the backward
evolution with no neutron LHAPDF set anywhere in the chain.  Feeding the
neutron set NNPDF40_nnlo_as_01180_n to either code with ih2 = 2 would swap
twice and silently generate a proton under a neutron label.  Validated by
powheg/production/validate.sh against proton beam + NNPDF40_nnlo_as_01180_n.

THE BEAM ENERGIES do not depend on the nucleon.  POWHEG-RES keeps
ebeam2 = 0.938 (the "below Pythia's proton mass, so at rest" trick recorded
in analysis/beams.py; it is below the neutron mass 0.93957 too), and
POWHEG-V2 takes sqrt(s)/2 with s built on M_P for BOTH nucleons -- so the p
and n runs have the same s, and the per-nucleon tungsten combination adds
cross-sections at one energy.  The analysis W cut uses M_P throughout.

THE GENERATION Q2 CUT STAYS the earlier production's (Qmin 1.5 / q2cut 2.25, i.e. Q2 > 2.25),
looser than the fiducial Q2 > 4.  The evidence is in PRODUCTION.md,
"Status / POWHEG".  No y cut: RES has ymin 0 / ymax 1, xmin 0 / xmax 1
already; V2 has no y parameter at all.

EVENTS PER UNIT.  RES runs `manyseeds` and every seed is one LHE file and one
shower job, numevts per seed; the driver adds seeds until the showered target
is reached, so dead seeds (the ISR upper-bound abort) cost nothing but time.
V2 runs one process per batch directory; the driver runs as many batches of
numevts as the target needs.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(REPO, "analysis"))

import beams  # noqa: E402

CHECK = "--check" in sys.argv

RES_TEMPLATE = os.path.join(REPO, "powheg", "cards", "POWHEG-RES",
                            "mu1TeV-wide", "powheg.input")
V2_TEMPLATE = os.path.join(REPO, "powheg", "cards", "POWHEG-V2",
                           "nu1TeV-prod", "powheg.input")
OUT = os.path.join(REPO, "powheg", "cards", "production")

TARGETS = {"p": (1, "proton"), "n": (2, "neutron")}

# Events per RES seed and per V2 batch.  1 TeV carries the differential
# distributions (1M showered per nucleon), the other energies the integrated
# rate (200k).  50k per RES seed matches the earlier production's 60k scale; the V2 batch size
# keeps each serial process to a few minutes.
RES_PER_SEED = {1000.0: 50000}
RES_PER_SEED_DEFAULT = 25000
V2_PER_BATCH = {1000.0: 260000}
V2_PER_BATCH_DEFAULT = 105000


def sub1(text, pattern, repl, what):
    new, n = re.subn(pattern, repl, text, flags=re.M)
    if n != 1:
        raise SystemExit(f"template: expected one {what}, matched {n}")
    return new


def res_card(e, t):
    b = beams.Beams("mu", e)
    ih2, name = TARGETS[t]
    text = open(RES_TEMPLATE).read()
    text = sub1(text, r"^! High-stats NLO run: NC DIS, 1 TeV mu- on proton at rest$",
                f"! PAPER-PLOTS-V2 production: NC DIS, {e:g} GeV mu- on a {name} "
                f"at rest\n"
                f"! GENERATED by powheg/production/make_cards.py from POWHEG-RES/"
                f"mu1TeV-wide -- edit that script, not this card.\n"
                f"! Driver: powheg/production/run_res.sh {e:g} {t}", "header")
    nev = RES_PER_SEED.get(e, RES_PER_SEED_DEFAULT)
    text = sub1(text, r"^numevts\s+\d+.*$",
                f"numevts {nev}        ! events per seed; the driver adds "
                f"seeds until the showered target is met", "numevts")
    text = sub1(text, r"^ih2\s+1\s.*$",
                f"ih2  {ih2}               ! hadron 2: {ih2} = {name}"
                + ("  (PROTON set below; POWHEG swaps u<->d itself)"
                   if t == "n" else ""), "ih2")
    text = sub1(text, r"^ebeam1\s+1000d0",
                f"ebeam1 {e:g}d0", "ebeam1")
    # the template's other literal energy statement
    text = text.replace("proton at rest (mass)",
                        "target at rest (0.938: see analysis/beams.py)")
    # lhans1/lhans2 stay 331100, the PROTON set, for both nucleons
    assert re.search(r"^lhans1\s+331100", text, re.M)
    assert re.search(r"^lhans2\s+331100", text, re.M)
    assert re.search(r"^Qmin\s+1\.5d0", text, re.M)
    assert re.search(r"^ymin\s+0d0", text, re.M)
    assert re.search(r"^ymax\s+1d0", text, re.M)
    assert re.search(r"^use-old-grid\s+1", text, re.M)
    return text


def v2_card(e, t):
    b = beams.Beams("nu", e)
    ih2, name = TARGETS[t]
    text = open(V2_TEMPLATE).read()
    eb = b.powheg_v2_ebeam
    for key in ("ebeam1", "ebeam2"):
        text = sub1(text, rf"^{key}\s+21\.66462758937933d0",
                    f"{key} {eb:.11f}d0", key)
    text = text.replace(
        "! POWHEG nu-DIS PRODUCTION run: 1 TeV nu_mu on a proton at rest, "
        "charged current",
        f"! PAPER-PLOTS-V2 production: {e:g} GeV nu_mu on a {name} at rest, "
        f"charged current\n"
        f"! GENERATED by powheg/production/make_cards.py from POWHEG-V2/nu1TeV-prod"
        f" -- edit that script, not this card.\n"
        f"! Driver: powheg/production/run_v2.sh {e:g} {t}\n"
        f"! ebeam = sqrt(s)/2 with s = M_P^2 + 2 E M_P = {b.s:.5f} GeV^2 for "
        f"BOTH nucleons.\n"
        f"! The v1 notes below on the 1 TeV proton reference and numevts are "
        f"inherited from the template.")
    nev = V2_PER_BATCH.get(e, V2_PER_BATCH_DEFAULT)
    # the whole earlier numevts note (a 3x-statistics history of the 1 TeV proton
    # sample) goes with the number it described
    text = sub1(text, r"^numevts\s+\d+.*\n(?:[ \t]+!.*\n)*",
                f"numevts {nev}    ! events per batch directory; the driver "
                f"runs as many batches as the showered target needs\n",
                "numevts")
    text = sub1(text, r"^ih2\s+1\s.*$",
                f"ih2   {ih2}            ! hadron 2: {ih2} = {name}"
                + ("  (PROTON set below; POWHEG swaps u<->d itself)"
                   if t == "n" else ""), "ih2")
    assert re.search(r"^lhans1 331100", text, re.M)
    assert re.search(r"^lhans2 331100", text, re.M)
    assert re.search(r"^q2cut 2\.25d0", text, re.M)
    assert re.search(r"^use-old-grid\s+1", text, re.M)
    # UNWEIGHTING EXCESS CORRECTION (2026-09-19, user: regenerate with it).
    # Without it every point where the true weight exceeds POWHEG's upper
    # bound is under-produced: 2-4k such points per batch, clustered at low x
    # and low Q2, left the tungsten x spectrum 6-9% low at x = 0.004-0.011
    # (pp02) while the total stayed right.  POWHEG-RES's cards always had it.
    # Evidence: PRODUCTION.md, "POWHEG-V2 low-x deficit".
    assert not re.search(r"^ubexcess_correct", text, re.M)
    text = text.rstrip("\n") + (
        "\nubexcess_correct 1  ! restore events above the unweighting bound "
        "(2026-09-19; see make_cards.py)\n")
    return text


def v2mc_card(e, t):
    """POWHEG-V2mc: the  POWHEG-V2 card with the earlier production's three massive-charm lines.

    User, 2026-09-14: "massive-charm run is still very much part of the
    plan ... (and launch the corresponding generation!)".  Exactly the
    changes between the earlier production's POWHEG-V2/nu1TeV-prod and POWHEG-V2mc/nu1TeV-prod:
    qmass 1.51d0 (the mass YADISM FONLL uses), numflav 4, and no iupperfsr
    (the massless-case FSR bound).  With qmass > 0 the massive charm IS the
    process: the sample is CHARM PRODUCTION, never an inclusive rate
    (memory/PRODUCTION: 20000 of 20000 earlier LHE events carry a charm).
    """
    text = v2_card(e, t)
    text = text.replace(f"run_v2.sh {e:g} {t}",
                        f"run_v2_mc.sh {e:g} {t}  (POWHEG-V2mc, MASSIVE charm)")
    text = sub1(text, r"^qmass\s+0d0.*$",
                "qmass  1.51d0      ! V2mc: MASSIVE charm, the YADISM FONLL value",
                "qmass")
    text = sub1(text, r"^numflav\s+5.*$",
                "numflav 4          ! V2mc: charm from the ME, 4 flavours in "
                "the nucleon", "numflav")
    text = sub1(text, r"^iupperfsr\s+1.*\n", "", "iupperfsr")
    return ("! POWHEG-V2mc -- POWHEG-V2 with MASSIVE CHARM (charm production "
            "only).\n" + text)


def write(path, text):
    rel = os.path.relpath(path, REPO)
    old = open(path).read() if os.path.exists(path) else None
    if old == text:
        print(f"  ok       {rel}")
        return 0
    print(f"  {'would write' if CHECK else ('rewrite  ' if old else 'create   ')}"
          f" {rel}")
    if not CHECK:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(text)
    return 1


def main():
    changed = 0
    # the SIDIS ladder adds 300 GeV for the two production codes (pion study,
    # beams.SIDIS_ENERGIES); POWHEG-V2mc, a charm-only entry, stays on the
    # energies
    for e in beams.SIDIS_ENERGIES:
        for t in TARGETS:
            tag = beams.Beams("mu", e).tag
            changed += write(os.path.join(OUT, "POWHEG-RES", f"mu{tag}-{t}",
                                          "powheg.input"), res_card(e, t))
            changed += write(os.path.join(OUT, "POWHEG-V2", f"nu{tag}-{t}",
                                          "powheg.input"), v2_card(e, t))
            if e in beams.BENCH_ENERGIES:
                changed += write(os.path.join(OUT, "POWHEG-V2mc", f"nu{tag}-{t}",
                                              "powheg.input"), v2mc_card(e, t))
    # below 300 GeV: POWHEG-V2 alone (beams.SIDIS_ENERGIES_LOW)
    for e in beams.SIDIS_ENERGIES_LOW:
        for t in TARGETS:
            tag = beams.Beams("nu", e).tag
            changed += write(os.path.join(OUT, "POWHEG-V2", f"nu{tag}-{t}",
                                          "powheg.input"), v2_card(e, t))
    print(f"{changed} card(s) {'would change' if CHECK else 'written'}.")


if __name__ == "__main__":
    main()
