#!/usr/bin/env bash
# The Herwig 7 POWHEG-NLO rows of the production (PRODUCTION.md).
#
# Usage: nohup /bin/bash herwig7/production/production.sh > logs/herwig_v2_production.log 2>&1 &
#        herwig7/production/production.sh --list      print the task list and exit
#
# Both currents, both nucleons (p and a genuine neutron beam, see
# make_cards.py), both halves of the NLO weight, the six SIDIS-ladder energies.  Every task
# is one Herwig job; at most MAXPAR run at once (shared machine).
#
# RE-INVOKE FREELY: a job whose events.hepmc and .out are complete and whose
# fingerprint matches the current card + plugin is skipped; an incomplete one
# is wiped and rerun with the SAME seed; a complete one built from a different
# card or plugin is REFUSED (never mixed, never overwritten).
#
# DO NOT EDIT THIS FILE WHILE IT RUNS (CONVENTIONS.md rule 1c).  The task list is
# generated here and nowhere else; to change statistics, wait for it to finish
# or kill the PARENT shell only and re-invoke.
#
# Statistics (per current, per nucleon):
#   1 TeV             pos 6 x 50k  + neg 4 x 50k     (500k, as the earlier production)
#   400/700/2000/4000 pos 4 x 20k  + neg 1 x 20k     (100k)
# The neg split: in the new region the negative half is 2.8% (p) / 3.1% (n)
# of the positive one on muon NC and 0.15% / 0.08% on neutrino CC (1 TeV,
# validate_neutron.sh), and for sigma = sigma+ - sigma- at a fixed number of
# events the variance is smallest with N-/N+ ~ sigma-/sigma+.  One neg job in
# five is still ~7x that on the muon side, so the neg half's own shape is not
# statistics-starved; the earlier production's 4 in 10 is kept at 1 TeV so the anchor matches the earlier production.
#
# RULE 1b: before every launch the free space on $PHYSICS24 must stay above
# V2_DISK_FLOOR_GB after this job AND every running one write their full
# estimated size (KB_PER_EVENT: measured 8.5-9.8 kB/event on the positive
# halves and 10.7-12.5 on the negative ones, taken at 13).  If not, nothing more is launched, the running jobs finish, and the
# driver exits 3.
set -u
HERE=$(cd "$(dirname "$0")" && pwd)
. "$HERE/lib.sh"
MAXPAR=10   # 2026-09-19 retry regeneration: 14 cores, the LHE arm takes the other 4
KB_PER_EVENT=13

# V2_CURRENTS limits the currents (default both).  The inclusive-hadron
# regeneration of 2026-09-30 needs the neutrino current alone.
CURS=${V2_CURRENTS:-"mu nu"}
tasks() {   # cur half t E N nev, in launch order
    local j cur t E
    # round-robin over (current, nucleon) so the first four jobs launched are
    # the four positive-half job 1s -- the first samples inspected
    for j in 1 2 3 4 5 6; do
        for cur in $CURS; do for t in p n; do
            echo "$cur pos $t 1000 $j 50000"
        done; done
        [ "$j" -le 4 ] || continue
        for cur in $CURS; do for t in p n; do
            echo "$cur neg $t 1000 $j 50000"
        done; done
    done
    # 300 GeV is the SIDIS-ladder point (beams.SIDIS_ENERGIES, pion
    # study, 2026-09-18), same statistics as the other off-anchor energies
    for E in 400 4000 700 2000 300; do
        for j in 1 2 3 4; do
            for cur in $CURS; do for t in p n; do
                echo "$cur pos $t $E $j 20000"
            done; done
            [ "$j" -eq 1 ] || continue
            for cur in $CURS; do for t in p n; do
                echo "$cur neg $t $E $j 20000"
            done; done
        done
    done
}

if [ "${1:-}" = "--list" ]; then
    tasks | awk '{n[$1" "$3]+=$6; t++} END {for (k in n) print "  " k, n[k], "events"; print "  " t, "jobs"}'
    tasks
    exit 0
fi

LOCK=$V2_BUILD/production.lock
mkdir -p "$V2_BUILD"
if ! mkdir "$LOCK" 2>/dev/null; then
    echo "another production.sh holds $LOCK -- refusing to run twice" >&2
    exit 1
fi
trap 'rmdir "$LOCK" 2>/dev/null' EXIT

echo "Herwig production start $(date)  (MAXPAR $MAXPAR, floor $V2_DISK_FLOOR_GB GB)"
python3 "$HERE/make_cards.py" --check | tail -1
if python3 "$HERE/make_cards.py" --check | grep -q "would write"; then
    echo "the cards on disk differ from make_cards.py -- run it first" >&2
    exit 1
fi

FAILED=$V2_BUILD/production.failed.log
: > "$FAILED"
TASKS=$V2_BUILD/production.tasks.log
tasks > "$TASKS"
# the task list is read on fd 3, never on stdin: a child that reads stdin
# would otherwise swallow the rest of the list (hw_env also closes stdin)
while read -r cur half t E N nev <&3; do
    stem=$(v2_stem "$cur" "$half" "$t" "$E")
    d=$(v2_jobdir "$cur" "$half" "$t" "$E" "$N")
    seed=$(v2_seed "$cur" "$half" "$t" "$E" "$N")
    v2_job_state "$d" "$stem" "$seed" "$nev"; st=$?
    if [ $st = 0 ]; then echo "  skip  $(basename "$d") (complete)"; continue; fi
    if [ $st = 2 ]; then
        echo "  REFUSE $(basename "$d"): complete, different card/plugin" | tee -a "$FAILED"
        continue
    fi
    while [ "$(jobs -pr | wc -l | tr -d ' ')" -ge "$MAXPAR" ]; do sleep 10; done
    running=$(jobs -pr | wc -l | tr -d ' ')
    need=$(( (running + 1) * nev * KB_PER_EVENT / 1048576 + 1 ))
    avail=$(v2_avail_gb)
    if [ $((avail - need)) -lt "$V2_DISK_FLOOR_GB" ]; then
        echo "DISK: ${avail} GB free, launching would reserve ${need} GB and cross" \
             "the ${V2_DISK_FLOOR_GB} GB floor -- stopping launches" | tee -a "$FAILED"
        break
    fi
    # compile HERE, in the single-threaded loop, so two jobs of one stem can
    # never race on its build directory
    v2_compile "$stem" || { echo "  compile failed: $stem" | tee -a "$FAILED"; continue; }
    ( v2_run_job "$cur" "$half" "$t" "$E" "$N" "$nev" \
        || echo "  FAILED $cur $half $t $E job $N" >> "$FAILED" ) < /dev/null &
done 3< "$TASKS"
wait

echo "Herwig production end $(date)"
if [ -s "$FAILED" ]; then
    echo "PROBLEMS:"; cat "$FAILED"
    grep -q "^DISK" "$FAILED" && exit 3
    exit 2
fi
echo "all tasks complete"
