#!/usr/bin/env python3
"""Every paper plot is in the paper, and the held-back ones are not.

WHY THIS GATE EXISTS.  The figures are generated by one script each and copied
into paper/figures/ by tools/sync_paper_figures.sh, which is a glob -- so a
figure can be produced, synced, tracked and never actually included by any
\\includegraphics, and nothing notices.  That is the quiet half of the user's
instruction that the paper "includes all the paper plots in the current
order"; the loud half, a figure INCLUDED that should not be, has its own
history: the single-inclusive pion figure was in the paper until the user
asked for it to be held back (2026-09-08: "The 'single-inclusive pion figure'
should not go yet into the paper, we will add it at a later stage"), and
nothing but a comment records that decision.

THE RULE.  A script in analysis/paper_plots/ with IN_PAPER = True must be
included by some paper/*.tex line that is not commented out; one without it
must NOT be.  Both directions are checked, because both have gone wrong.

Usage: tools/check_paper_figures_used.py
"""
import glob
import importlib.util
import os
import re
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE, "analysis"))

INCLUDE = re.compile(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]*)\}")


def included():
    """Basenames of every figure the document actually includes.

    A LINE THAT STARTS WITH A COMMENT DOES NOT COUNT, which is the whole
    point: the pion figure is present in bench-sec-rates.tex as a commented
    block, and reading it as "included" would defeat the check.  A stray %
    mid-line is not treated as a comment, since \\% is legal LaTeX and this
    only has to be right for whole-line comments, which is how figures are
    held back here.
    """
    out = set()
    for p in sorted(glob.glob(os.path.join(BASE, "paper", "*.tex"))):
        for line in open(p):
            if line.lstrip().startswith("%"):
                continue
            for m in INCLUDE.finditer(line):
                out.add(os.path.basename(m.group(1)))
    return out


def _load(p, prefix):
    slug = os.path.basename(p)[:-3]
    spec = importlib.util.spec_from_file_location(prefix + slug, p)
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return slug, m


def main():
    have = included()
    bad = []
    seen = 0
    # >>> ONLY THE  FIGURES EXIST (user, 2026-09-19). <<<  The earlier scripts in
    # analysis/paper_plots/ were deleted with the 0.2 < y < 0.9 results.  A 
    # script that declares IN_PAPER = True must have its output in the
    # document; one without it must not be there.
    for p in sorted(glob.glob(os.path.join(BASE, "analysis",
                                           "paper_plots", "pp*.py"))):
        slug, m = _load(p, "pp2_")
        inp = bool(getattr(m, "IN_PAPER", False))
        seen += 1
        ok = inp == (m.OUTPUT in have)
        if not ok:
            bad.append(f"{slug}: IN_PAPER={inp} but {m.OUTPUT} is "
                       f"{'not ' if inp else ''}included by the paper")
        print(f"  {'ok  ' if ok else 'FAIL'}   {slug:29s} "
              f"{'IN_PAPER' if inp else 'report':8s} "
              f"{'in the paper' if m.OUTPUT in have else 'held back'}")
    # AND EVERY INCLUDED FIGURE IS ON DISK: a figure the document still names
    # after its file was deleted (the earlier paper_*.png, 2026-09-19) would only
    # surface as a LaTeX error in Overleaf.
    figdir = os.path.join(BASE, "paper", "figures")
    for name in sorted(have):
        if not os.path.exists(os.path.join(figdir, name)):
            bad.append(f"{name} is included by the paper but is not in "
                       f"paper/figures/")
    print()
    for b in bad:
        print(f"  {b}")
    if bad:
        return 1
    print(f"all {seen} paper plot(s) are where their IN_PAPER flag says, and "
          f"every included figure is on disk")
    return 0


if __name__ == "__main__":
    sys.exit(main())
