#!/usr/bin/env python3
"""Emit the per-energy generator cards for the energy scan.

The 1 TeV cards are the templates and are NEVER touched: they produced every
published sample, so rewriting them would silently invalidate the page.  This
writes the other energies beside them, taking every beam number from
analysis/beams.py so a card cannot disagree with the analytic reference.

    tools/make_energy_cards.py            # write the cards
    tools/make_energy_cards.py --check    # report what would change

Covers BOTH currents (CONVENTIONS.md rule 2b): Pythia 8, Sherpa LO,
Herwig LO, POWHEG-RES (muon NLO) and POWHEG-V2 (neutrino).  The others follow the same pattern when they are added.

NOTE on the anchor's known inconsistency: the committed 1 TeV muon cards sit
at 2 k.P = 1874.68 (as if E_mu = 998.94) while beams.py gives 1876.544 -- see
KNOWN_MISMATCH in analysis/beams.py.  The new cards are CORRECT, which leaves
1 TeV very slightly inconsistent with the rest of the scan.  That trade was
recorded when beams.py was written; it is worth -0.019% on sigma.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(REPO, "analysis"))

import beams  # noqa: E402

CHECK = "--check" in sys.argv

# ONE ENERGY OFF THE SCAN, and only the cards that need it (2026-09-07).
# arXiv:2504.05376 predicts the pion multiplicity at E_nu ~ 300 GeV, and the
# user asked for the comparison to be made at THAT energy rather than at our
# nearest.  300 GeV is therefore a COMPARISON POINT, not a fourth benchmark
# energy: it must not enter beams.ENERGIES, because that tuple drives the
# cross-section ladders the FASER rates ride and every result filename in the
# scan.  So it is written here, on request, for the one generator the
# comparison uses.
#
#   tools/make_energy_cards.py --extra 300     # POWHEG-V2 neutrino card only
EXTRA = None
if "--extra" in sys.argv:
    EXTRA = float(sys.argv[sys.argv.index("--extra") + 1])


def write(path, text):
    """Write a card, reporting what changed; never clobbers silently."""
    rel = os.path.relpath(path, REPO)
    old = open(path).read() if os.path.exists(path) else None
    if old == text:
        print(f"  ok       {rel}")
        return 0
    verb = "would write" if CHECK else ("rewrite  " if old else "create   ")
    print(f"  {verb} {rel}")
    if not CHECK:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(text)
    return 1


# --------------------------------------------------------------------- Pythia
def pythia_card(b):
    """The 1 TeV card with the beam energy and the header swapped."""
    src = os.path.join(REPO, "pythia8", "dis_mu1TeV.cmnd")
    text = open(src).read()
    text = text.replace(
        "! Fixed-target NC muon DIS benchmark: 1 TeV mu- on proton at rest.",
        f"! Fixed-target NC muon DIS benchmark: {b.e_lab:g} GeV mu- on proton"
        f" at rest.\n"
        f"! GENERATED by tools/make_energy_cards.py from dis_mu1TeV.cmnd --"
        f" edit that one.")
    text = text.replace(
        "! beams: mu- (1 TeV) on proton at rest (eB below mass -> at rest)",
        f"! beams: mu- ({b.tag}) on proton at rest (eB below mass -> at rest)")
    old_e = "Beams:eA = 1000."
    assert old_e in text, "the Pythia template no longer sets Beams:eA = 1000."
    text = text.replace(old_e, f"Beams:eA = {b.e_lab:g}.")
    return text


# --------------------------------------------------------------------- Sherpa
def sherpa_card(b):
    """The LO card with the c.m. beam energies swapped."""
    src = os.path.join(REPO, "sherpa", "Runs", "MuonDIS_LO", "Sherpa.yaml")
    text = open(src).read()
    ea, eb = b.cm_energies
    text = text.replace(
        "# Neutral-current muon DIS, fixed target: 1 TeV mu- beam on proton at rest.",
        f"# Neutral-current muon DIS, fixed target: {b.e_lab:g} GeV mu- beam on"
        f" proton at rest.\n"
        f"# GENERATED by tools/make_energy_cards.py from ../MuonDIS_LO --"
        f" edit that one.")
    text = text.replace("(sqrt(s)=43.33 GeV)", f"(sqrt(s)={b.sqrt_s:.2f} GeV)")
    old_e = "BEAM_ENERGIES: [21.6438, 21.6641]"
    assert old_e in text, "the Sherpa template no longer sets the 1 TeV beams"
    text = text.replace(old_e, f"BEAM_ENERGIES: [{ea:.6f}, {eb:.6f}]")
    return text


def sherpa_nlo_card(b):
    """The MUON MC@NLO card with the c.m. beam energies swapped.

    MUON ONLY, deliberately.  The neutrino NLO card (../NuDIS_NLO) is NOT
    generated per energy, because it carries a physics compromise the muon one
    does not: it must run Order: 0 (unit CKM), since full CKM switches on the
    Cabibbo cross-family channels and Sherpa's only loop provider in this build
    refuses them ("Couldn't find virtual ME for this process").  Its charm
    fraction is therefore ~17% against the LO card's correct ~20%, so a
    neutrino NLO point is not like-for-like with its own LO.  Extending it to
    new energies would propagate that, and the neutrino NLO axis is already
    covered by Herwig POWHEG without the compromise.  See that card's header.
    """
    src = os.path.join(REPO, "sherpa", "Runs", "MuonDIS_NLO", "Sherpa.yaml")
    text = open(src).read()
    ea, eb = b.cm_energies
    old_e = "BEAM_ENERGIES: [21.6438, 21.6641]"
    assert old_e in text, "the Sherpa NLO template no longer sets the 1 TeV beams"
    text = text.replace(old_e, f"BEAM_ENERGIES: [{ea:.6f}, {eb:.6f}]")
    # the inherited header states the beam as a LITERAL; left alone it says
    # "1 TeV" at the top of a 4 TeV card, which is how a stale comment outlives
    # the number it describes
    text = text.replace(
        "# Neutral-current muon DIS, fixed target: 1 TeV mu- beam on proton at rest.",
        f"# Neutral-current muon DIS, fixed target: {b.e_lab:g} GeV mu- beam on"
        f" proton at rest.")
    text = text.replace("(sqrt(s)=43.33 GeV,", f"(sqrt(s)={b.sqrt_s:.2f} GeV,")
    return (f"# GENERATED by tools/make_energy_cards.py from ../MuonDIS_NLO"
            f" -- edit that one.\n"
            f"# {b.e_lab:g} GeV mu- on a proton at rest, sqrt(s) ="
            f" {b.sqrt_s:.2f} GeV.\n" + text)


# --------------------------------------------------------------------- Herwig
# The POWHEG-MATCHED NLO cards, both currents.  Only the two BeamEMax lines and
# the saverun name depend on the beam, exactly as for the LO cards.
#
# EACH ENERGY NEEDS BOTH HALVES.  Herwig's DISBase splits the NLO weight into
# its positive and negative parts and generates them as two separate
# positive-weight samples, selected by the Contribution switch; the physical
# result is pos - neg, assembled by herwig7/combine_nlo.py.  Herwig's default
# puts Contribution 1 on PowhegMEDIS, so a single run is only HALF the answer
# -- trap 5 in the Herwig notes.  Generating only the PWG card at a new energy
# would therefore produce a plausible, wrong, too-large NLO cross-section.
HERWIG_PWG_CARDS = [
    # (src, saverun stem, current)
    ("DIS-mu-POWHEG.in", "DIS-mu-PWG",    "mu"),
    ("DIS-mu-PWGNEG.in", "DIS-mu-PWGNEG", "mu"),
    ("DIS-nu-POWHEG.in", "DIS-nu-PWG",    "nu"),
    ("DIS-nu-PWGNEG.in", "DIS-nu-PWGNEG", "nu"),
]


def herwig_pwg_card(b, src_name, save_stem):
    """A POWHEG-matched NLO card with the c.m. beam energies swapped."""
    src = os.path.join(REPO, "herwig7", src_name)
    text = open(src).read()
    ea, eb = b.cm_energies
    old_save = f"saverun {save_stem} EventGenerator"
    assert old_save in text, f"{src_name} no longer ends with {old_save!r}"
    text = text.replace(old_save, f"saverun {save_stem}-{b.tag} EventGenerator")
    n = 0
    for line in text.splitlines():
        ls = line.strip()
        if ls.startswith("set Luminosity:BeamEMaxA"):
            text = text.replace(line, f"set Luminosity:BeamEMaxA {ea:.6f}*GeV")
            n += 1
        elif ls.startswith("set Luminosity:BeamEMaxB"):
            text = text.replace(line, f"set Luminosity:BeamEMaxB {eb:.6f}*GeV")
            n += 1
    assert n == 2, f"{src_name}: expected 2 BeamEMax lines, replaced {n}"
    return (f"# GENERATED by tools/make_energy_cards.py from {src_name}"
            f" -- edit that one.\n"
            f"# beams E = [{ea:.6f}, {eb:.6f}] GeV, "
            f"sqrt(s) = {b.sqrt_s:.2f} GeV, E_lab = {b.e_lab:g} GeV\n" + text)


def herwig_card(b, src_name="DIS-mu.in"):
    """The LO card with the c.m. beam energies swapped.

    Only the two Luminosity:BeamEMax lines depend on the beam: MinQ2 is the
    fiducial cut and MaxQ2 is already 1e6 GeV2, comfortably above the 6748
    that 4 TeV reaches.  (MaxQ2 matters -- ThePEG's SimpleDISCut defaults it to
    100 GeV2 and vetoes silently above that; see the card's own TRAP note.)
    """
    src = os.path.join(REPO, "herwig7", src_name)
    text = open(src).read()
    ea, eb = b.cm_energies
    text = text.replace(
        "# beams [mu-, p+] with E = [21.6438, 21.6641] GeV (sqrt(s) = 43.33 GeV),",
        f"# beams [mu-, p+] with E = [{ea:.6f}, {eb:.6f}] GeV "
        f"(sqrt(s) = {b.sqrt_s:.2f} GeV),\n"
        f"# GENERATED by tools/make_energy_cards.py from {src_name} -- edit that one.")
    # THE saverun LINE NAMES THE OUTPUT.  Left as "saverun DIS-mu", reading
    # this card writes DIS-mu.run -- CLOBBERING the 1 TeV compiled run file
    # with another energy's beams, silently.  It did exactly that once.
    old_save = "saverun DIS-mu EventGenerator"
    assert old_save in text, f"{src_name} no longer ends with {old_save!r}"
    text = text.replace(old_save, f"saverun DIS-mu-{b.tag} EventGenerator")

    for old_e, new_e in (("set Luminosity:BeamEMaxA 21.6438*GeV",
                          f"set Luminosity:BeamEMaxA {ea:.6f}*GeV"),
                         ("set Luminosity:BeamEMaxB 21.6641*GeV",
                          f"set Luminosity:BeamEMaxB {eb:.6f}*GeV")):
        assert old_e in text, f"{src_name} no longer sets {old_e!r}"
        text = text.replace(old_e, new_e)
    return text


# --------------------------------------------------------------------- POWHEG
def powheg_res_card(b):
    """POWHEG-RES card with the lab beam energy swapped.

    `fixed_target 1` means ebeam1 is the LAB lepton energy and ebeam2 the
    target mass, so only ebeam1 tracks the scan.

    ebeam2 STAYS AT 0.938, and must not be "corrected" to the benchmark's
    m_p = 0.938272.  That value is not sloppiness: POWHEG writes it into the
    LHE <init> line as beam 2's ENERGY, and Pythia's proton mass is 0.93827.
    Below that, Pythia reads the target as AT REST -- the same trick the
    Pythia card uses with `Beams:eB = 0.` ("eB below mass -> at rest").  Set
    to 0.938272 it sits just ABOVE m_p, so Pythia tries to build a moving
    proton and every event dies with

        Error in ProcessContainer::constructProcess: setting mass failed

    which is exactly what happened: 12000 aborts and 0 events per job at
    400 GeV.  So the 0.029% difference in s recorded as an anchor
    inconsistency in analysis/beams.py is deliberate and load-bearing.

    Qmax stays at 10000: 4 TeV reaches Q2 = 6748, i.e. Q = 82, far below it.
    """
    src = os.path.join(REPO, "powheg", "cards", "POWHEG-RES", "mu1TeV-wide",
                       "powheg.input")
    text = open(src).read()
    text = text.replace(
        "! High-stats NLO run: NC DIS, 1 TeV mu- on proton at rest",
        f"! High-stats NLO run: NC DIS, {b.e_lab:g} GeV mu- on proton at rest\n"
        f"! GENERATED by tools/make_energy_cards.py from mu1TeV-wide -- edit that one.")
    old_e = "ebeam1 1000d0"
    assert old_e in text, "the POWHEG-RES template no longer sets ebeam1 1000d0"
    text = text.replace(old_e, f"ebeam1 {b.e_lab:g}d0")
    return text


# ------------------------------------------------------------------ neutrino
# CONVENTIONS.md rule 2b: whatever exists on the muon NC side is owed on the
# neutrino CC side.  The neutrino cards are EXACT at 1 TeV on all three
# generators (see beams.KNOWN_MISMATCH -- it is the muon ones that sit at
# E = 998.94), so these are straight substitutions with nothing to preserve.
def pythia_nu_card(b):
    src = os.path.join(REPO, "pythia8", "dis_nu1TeV.cmnd")
    text = open(src).read()
    old_e = "Beams:eA = 1000."
    assert old_e in text, "the Pythia nu template no longer sets Beams:eA = 1000."
    text = text.replace(old_e, f"Beams:eA = {b.e_lab:g}.")
    return ("! GENERATED by tools/make_energy_cards.py from dis_nu1TeV.cmnd"
            " -- edit that one.\n") + text


def herwig_nu_card(b):
    """From DIS-nu-POL.in, the POLARIZED card -- NOT DIS-nu.in.

    This matters by a factor of two.  DIS-nu.in leaves the neutrino beam
    unpolarised, so Herwig spin-averages over two incoming helicities when a
    massless neutrino has only one, and the cross-section comes out HALVED.
    DIS-nu-POL.in declares the beam as PolarizedBeamParticleData with
    LongitudinalPolarization = -1, which is why analyze_nu.py carries
    HERWIG_NU_SPIN_FACTOR = 1.0 and why the published 1 TeV sample lives in
    nu_job_*/DIS-nu-POL-S*.out.

    Generating from DIS-nu.in put Herwig at exactly ratio 0.5 to YADISM at
    400 GeV and 4 TeV while 1 TeV sat on 1.0 -- visible the moment the
    neutrino panel of cmp_sigma_vs_E was drawn.
    """
    src = os.path.join(REPO, "herwig7", "DIS-nu-POL.in")
    text = open(src).read()
    ea, eb = b.cm_energies
    # saverun names the OUTPUT; leaving it would clobber the 1 TeV run file
    old_save = "saverun DIS-nu-POL EventGenerator"
    assert old_save in text, "DIS-nu-POL.in no longer ends with saverun DIS-nu-POL"
    text = text.replace(old_save, f"saverun DIS-nu-POL-{b.tag} EventGenerator")
    for old_e, new_e in (("set Luminosity:BeamEMaxA 21.654469*GeV",
                          f"set Luminosity:BeamEMaxA {ea:.6f}*GeV"),
                         ("set Luminosity:BeamEMaxB 21.674786*GeV",
                          f"set Luminosity:BeamEMaxB {eb:.6f}*GeV")):
        assert old_e in text, f"DIS-nu.in no longer sets {old_e!r}"
        text = text.replace(old_e, new_e)
    return ("# GENERATED by tools/make_energy_cards.py from DIS-nu.in"
            " -- edit that one.\n") + text


def sherpa_nu_card(b):
    src = os.path.join(REPO, "sherpa", "Runs", "NuDIS_LO", "Sherpa.yaml")
    text = open(src).read()
    ea, eb = b.cm_energies
    old_e = "BEAM_ENERGIES: [21.654469, 21.674786]"
    assert old_e in text, "NuDIS_LO no longer sets the 1 TeV beams"
    text = text.replace(old_e, f"BEAM_ENERGIES: [{ea:.6f}, {eb:.6f}]")
    return ("# GENERATED by tools/make_energy_cards.py from ../NuDIS_LO"
            " -- edit that one.\n") + text


def powheg_v2_card(b):
    """POWHEG-V2 wants a SYMMETRIC c.m. pair, not the fixed-target form."""
    src = os.path.join(REPO, "powheg", "cards", "POWHEG-V2", "nu1TeV-prod",
                       "powheg.input")
    text = open(src).read()
    e = b.powheg_v2_ebeam
    for key in ("ebeam1", "ebeam2"):
        old_e = f"{key} 21.66462758937933d0"
        assert old_e in text, f"the POWHEG-V2 template no longer sets {old_e!r}"
        text = text.replace(old_e, f"{key} {e:.11f}d0")
    return ("! GENERATED by tools/make_energy_cards.py from nu1TeV-prod"
            " -- edit that one.\n") + text


def main():
    changed = 0
    if EXTRA is not None:
        b = beams.Beams("nu", EXTRA)
        print(f"off-scan comparison point {EXTRA:g} GeV [{b.tag}], "
              "POWHEG-V2 neutrino only:")
        changed += write(os.path.join(REPO, "powheg", "cards", "POWHEG-V2",
                                      f"nu{b.tag}-prod", "powheg.input"),
                         powheg_v2_card(b))
        print(f"\n{changed} card(s) {'would change' if CHECK else 'written'}.")
        return
    print("Pythia 8 cards:")
    for e in beams.ENERGIES:
        if e == beams.ANCHOR_ENERGY:
            continue                      # the template; never regenerated
        b = beams.Beams("mu", e)
        changed += write(
            os.path.join(REPO, "pythia8", f"dis_mu{b.tag}.cmnd"), pythia_card(b))

    print("Sherpa LO cards:")
    runner = open(os.path.join(REPO, "sherpa", "Runs", "MuonDIS_LO",
                               "run_parallel.sh")).read()
    for e in beams.ENERGIES:
        if e == beams.ANCHOR_ENERGY:
            continue
        b = beams.Beams("mu", e)
        d = os.path.join(REPO, "sherpa", "Runs", f"MuonDIS_LO_{b.tag}")
        changed += write(os.path.join(d, "Sherpa.yaml"), sherpa_card(b))
        # the parallel-run script is energy-independent; copied rather than
        # shared so link_cards.sh installs one per run dir, as it does for
        # every other Sherpa run
        changed += write(os.path.join(d, "run_parallel.sh"), runner)
        os.chmod(os.path.join(d, "run_parallel.sh"), 0o755)

    print("Herwig LO cards:")
    for e in beams.ENERGIES:
        if e == beams.ANCHOR_ENERGY:
            continue
        b = beams.Beams("mu", e)
        changed += write(
            os.path.join(REPO, "herwig7", f"DIS-mu-{b.tag}.in"), herwig_card(b))

    print("POWHEG-RES cards:")
    for e in beams.ENERGIES:
        if e == beams.ANCHOR_ENERGY:
            continue
        b = beams.Beams("mu", e)
        changed += write(
            os.path.join(REPO, "powheg", "cards", "POWHEG-RES",
                         f"mu{b.tag}-wide", "powheg.input"), powheg_res_card(b))

    print("Sherpa MC@NLO cards (MUON only -- see sherpa_nlo_card):")
    nlo_runner = open(os.path.join(REPO, "sherpa", "Runs", "MuonDIS_NLO",
                                   "run_parallel.sh")).read()
    for e in beams.ENERGIES:
        if e == beams.ANCHOR_ENERGY:
            continue
        b = beams.Beams("mu", e)
        d = os.path.join(REPO, "sherpa", "Runs", f"MuonDIS_NLO_{b.tag}")
        changed += write(os.path.join(d, "Sherpa.yaml"), sherpa_nlo_card(b))
        changed += write(os.path.join(d, "run_parallel.sh"), nlo_runner)
        os.chmod(os.path.join(d, "run_parallel.sh"), 0o755)

    print("Herwig POWHEG-matched NLO cards (both currents, both halves):")
    for e in beams.ENERGIES:
        if e == beams.ANCHOR_ENERGY:
            continue
        for src, stem, cur in HERWIG_PWG_CARDS:
            b = beams.Beams(cur, e)
            changed += write(
                os.path.join(REPO, "herwig7", f"{stem}-{b.tag}.in"),
                herwig_pwg_card(b, src, stem))

    print("Neutrino cards (Pythia / Herwig / Sherpa LO / POWHEG-V2):")
    nu_runner = open(os.path.join(REPO, "sherpa", "Runs", "NuDIS_LO",
                                  "run_parallel.sh")).read()
    for e in beams.ENERGIES:
        if e == beams.ANCHOR_ENERGY:
            continue
        b = beams.Beams("nu", e)
        changed += write(os.path.join(REPO, "pythia8", f"dis_nu{b.tag}.cmnd"),
                         pythia_nu_card(b))
        changed += write(
            os.path.join(REPO, "herwig7", f"DIS-nu-POL-{b.tag}.in"),
            herwig_nu_card(b))
        d = os.path.join(REPO, "sherpa", "Runs", f"NuDIS_LO_{b.tag}")
        changed += write(os.path.join(d, "Sherpa.yaml"), sherpa_nu_card(b))
        changed += write(os.path.join(d, "run_parallel.sh"), nu_runner)
        os.chmod(os.path.join(d, "run_parallel.sh"), 0o755)
        changed += write(os.path.join(REPO, "powheg", "cards", "POWHEG-V2",
                                      f"nu{b.tag}-prod", "powheg.input"),
                         powheg_v2_card(b))

    print(f"\n{changed} card(s) {'would change' if CHECK else 'written'}.")
    if not CHECK and changed:
        print("Sherpa run dirs are new: run ./tools/link_cards.sh to symlink\n"
              "them into the install tree, then integrate before generating.")


if __name__ == "__main__":
    main()
