#!/usr/bin/env python3
"""Write paper/table-faser-run34.tex from results_nu/faser_run34.json.

THE TABLE IS GENERATED, NOT TYPED.  Every other quantitative statement in the
paper is re-derived from the result JSONs by tools/check_paper_claims.py; a
table of two dozen numbers maintained by hand would be the one place that
could drift, and it is also the place where drift is hardest to see.  So the
LaTeX is written from the JSON and the JSON is written from the rates.

Usage: tools/make_run34_table.py
"""
import json
import os
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SRC = f"{BASE}/results_nu/faser_run34.json"
OUT = f"{BASE}/paper/table-faser-run34.tex"

# Which rows, in which order, and what to call them in the table.
#
# >>> THE KEYS DIFFER BETWEEN THE TWO CURRENTS AND THE TABLE MUST KNOW IT.
# <<<  `genie` is the DEFAULT tune on the muon side (there is no HEDIS for a
# charged lepton) and HEDIS on the neutrino side, where the default tune is
# `genie_lo`; Herwig is `herwig_nlo_powheg_full` on one and
# `herwig_nlo_full` on the other.  A single list would have silently put
# HEDIS in a row labelled "default tune" -- and the default tune is the one
# FASER runs, which is the whole reason the row is here (CONVENTIONS.md rule 1b).
ROWS = {
    "mu": [("powheg", r"\powhegres"),
           ("sherpa", r"\sherpa"),
           ("herwig_nlo_powheg_full", r"\herwig"),
           ("genie", r"\genie\ (default tune)")],
    "nu": [("powheg_nu", r"\powhegtwo"),
           ("sherpa_nlo", r"\sherpa"),
           ("herwig_nlo_full", r"\herwig"),
           ("genie_lo", r"\genie\ (default tune)")],
}
BLOCKS = [("nu", r"$\nu_\mu$ charged current"),
          ("mu", r"$\mu^-$ neutral current")]
SELS = [("inclusive", "inclusive"), ("faser_s", r"FASER$\nu$ (tracking)"),
        ("faser_e", r"FASER$\nu$ (emulsion)")]


def fmt(x):
    if x is None:
        return "---"
    if x >= 1e4:
        return f"${x/1000.0:.1f}\\times 10^{{3}}$"
    return f"${x:.0f}$"


def main():
    if not os.path.exists(SRC):
        sys.exit(f"{SRC} not found -- run analysis/faser_run34.py")
    with open(SRC) as f:
        d = json.load(f)
    l3, l34 = d["lumi_run3_fb"], d["lumi_run34_fb"]
    rel = d["flux_rel_err"]
    out = []
    out.append("% GENERATED by tools/make_run34_table.py -- do not edit.")
    out.append("% Numbers come from results_nu/faser_run34.json.")
    out.append(r"\begin{table}[t]")
    out.append(r"  \centering")
    out.append(r"  \small")
    out.append(r"  \begin{tabular}{llrr}")
    out.append(r"    \toprule")
    out.append(r"    & & \multicolumn{1}{c}{Run~3} "
               r"& \multicolumn{1}{c}{Run~3\,+\,Run~4} \\")
    out.append(rf"    & & \multicolumn{{1}}{{c}}{{${l3:.0f}$~fb$^{{-1}}$}} "
               rf"& \multicolumn{{1}}{{c}}{{${l34:.0f}$~fb$^{{-1}}$}} \\")
    out.append(r"    \midrule")
    for cur, title in BLOCKS:
        out.append(rf"    \multicolumn{{4}}{{l}}{{\emph{{{title}}}}} \\")
        for sel, selname in SELS:
            blk = d["rates"].get(f"{cur}_{sel}")
            if not blk:
                continue
            first = True
            for key, lab in ROWS[cur]:
                g = blk["generators"].get(key)
                if not g:
                    continue
                if "default tune" in lab and "G18_02a" not in (g["label"] or ""):
                    sys.exit(f"{cur}/{sel}: {key} is {g['label']!r}, which is "
                             f"not the default tune -- refusing to label it "
                             f"as one")
                left = selname if first else ""
                first = False
                out.append(rf"    {left} & {lab} & {fmt(g['run3'])} "
                           rf"& {fmt(g['run34'])} \\")
            out.append(r"    \addlinespace[2pt]")
    out.append(r"    \bottomrule")
    out.append(r"  \end{tabular}")
    out.append(
        r"  \caption{Expected numbers of interactions in FASER$\nu$, for the "
        rf"Run-3 integrated luminosity of ${l3:.0f}$~fb$^{{-1}}$ and for "
        rf"${l34:.0f}$~fb$^{{-1}}$, a provisional value for Run~3 and Run~4 "
        r"combined.  The dependence on the luminosity is linear, so a "
        r"different value rescales every entry.  The target is the present "
        r"$1.1$~t FASER$\nu$ tungsten detector and the fluxes are those of "
        r"Refs.~\cite{FASER:2024ykc,Francener:2025pnr}; the neutrino rates "
        rf"carry a flux uncertainty of $+{100*rel['hi']:.1f}\%/"
        rf"-{100*rel['lo']:.1f}\%$ from Ref.~\cite{{FASER:2024ykc}}, which is "
        r"common to every row and is not repeated in the table.}")
    out.append(r"  \label{tab:faser-run34}")
    out.append(r"\end{table}")
    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
