#!/usr/bin/env bash
# Sherpa MC@NLO for PAPER PLOTS: muon NC and neutrino CC, proton and
# neutron, at beams.BENCH_ENERGIES, in the final region (PRODUCTION.md).
#
# Usage:
#   tools/sherpa_production.sh run   [TARGETS]     # production, default TARGETS="p n"
#   tools/sherpa_production.sh check               # the neutron-beam validation arms
#   tools/sherpa_production.sh status              # what is done, per run dir
#   tools/sherpa_production.sh ahadic              # AHADIC failure counts, per job
#
# Knobs: MAXJOBS (default 5, the shared-machine ceiling), CURRENTS (default
# "nu mu"), ENERGIES (default beams.BENCH_ENERGIES), DISK_FLOOR_GB (default 155),
# SHOWER (default CSS).
#
# SHOWER=Dire IS THE SHOWER-STUDY TWIN (paper plot 9, user 2026-09-14): the
# same committed card, run with "SHOWER_GENERATOR: Dire" on the command line,
# into $SHERPA_RUNS/<the CSS name>_Dire (V2_MuonDIS_NLO_n_Dire, ...), 1 TeV
# only unless ENERGIES says otherwise.  EACH TWIN INTEGRATES ITSELF: the
# MC@NLO subtraction is built from the shower's kernels, so the BVI/RS split
# differs by a factor ~30 between CSS and Dire while the total agrees
# (measured in the earlier production, sherpa/run_sherpa_shower.sh) -- a borrowed Results.zip
# would pin the right total over the wrong S/H event population, silently.
# The compiled Process/ libraries are shower-independent and shared.
# Run it under nohup with a log in logs/; it skips every piece whose output is
# already complete, so re-invoking it after a stop costs nothing.
#
# >>> CONVENTIONS.md 1c: DO NOT EDIT THIS FILE WHILE IT IS RUNNING. <<<
#     ps -eo pid,command | grep "[v]2_sherpa.sh"
#
# LAYOUT (PRODUCTION.md): $SHERPA_RUNS/V2_{MuonDIS,NuDIS}_NLO_<t>[_TAG]/
# with integ.log + Results.zip at the top and job_N/evtfull below.  The card
# is sherpa/Runs/<same name>/Sherpa.yaml in this repo, written by
# tools/make_sherpa_cards.py, and the run dir holds a SYMLINK to it.
#
# STATISTICS: 8 x 25k at 1 TeV, 2 x 25k elsewhere, per target per current.
#
# SEEDS: integration at Sherpa's default seed, as in the earlier production.  Generation
# RANDOM_SEED = 1234+i on the proton (the earlier run_parallel.sh convention) and
# 5234+i on the neutron, so the two nucleons that are ADDED into tungsten
# never share a random stream.
#
# EACH RUN DIR INTEGRATES ITSELF.  Nothing shares a Results.zip across beams,
# energies or selectors: the integrator pins the total while the event
# population follows the grid, so a borrowed grid fails silently
# (tools/wcut_sherpa.sh).  Only the compiled Process/ libraries are shared,
# because they depend on the partonic process alone: ONE COPY per current,
# taken from the earlier production dir into the 1 TeV proton run dir (never a
# link into the earlier dir -- this production must not write into it), and every
# other dir of that current links to the copy.
#
# THE NEUTRON IS A GENUINE 2112 BEAM, RUN FROM A PATCHED COPY OF SHERPA
# (user decision 2026-09-13, "patched copy for neutron runs").  Stock 3.0.5
# segfaults on the first event of a 2112 beam (Hadron_Remnant::RemnantFlavour
# builds kf 21101 / 201); patches/sherpa-hadron-remnant-neutron.diff fixes it
# and tools/build_sherpa_npatch.sh builds it into $SHERPA_NPATCH (config.sh).
# EVERY Sherpa process in a neutron dir -- integration and generation -- runs
# $SHERPA_NPATCH/bin/Sherpa with SHERPA_LIBRARY_PATH / SHERPA_SHARE_PATH
# pointed at the copy.  The proton dirs keep the shared install, untouched.
#
# >>> THE LOADED LIBRARY IS CHECKED INSIDE EVERY NEUTRON JOB, NOT ASSUMED. <<<
# libcheck() finds the running Sherpa by its working directory and lists the
# dylibs it has mapped (lsof): libRemnants must be the copy's and nothing may
# come from the shared lib dir, or the job is killed.  The list is kept as
# job_N/mapped_libs.txt.  Then tools/sherpa_check_events.py reads every
# event: beam 2112, target valence (u,d) = (1,2), no uu diquark
# (job_N/remnant_check.txt).  A neutron job counts as done only with both.
# The event check is the one that cannot be fooled: the superseded neutron
# runs (a 2212 beam carrying the neutron PDF) gave perfectly good-looking
# cross-sections with a PROTON remnant.
#
# REUSED INTEGRATIONS.  A neutron dir whose Results.zip came from the old
# proton-beam + neutron-PDF card (integ.log says "Beam 2: P+") is not
# re-integrated: that grid is accepted by the 2112 card and gives the same
# cross-section (PRODUCTION.md has the test).  The old log is kept as
# integ_pbeam_npdf.log, the dir is re-run with `-e 0` on the 2112 card, and
# the reuse is refused -- the dir cleared and integrated afresh -- unless the
# new log says "Beam 2: n", did not re-integrate, and repeats BVI and RS to
# 1e-5.  A PARTIAL old integration (killed before it finished) is cleared.
#
# RESTARTS.  Work in progress is recognised from the working directory of
# every running Sherpa process (lsof), not from this shell's own job table,
# so a driver killed and re-invoked while its children are still running
# neither double-starts an integration nor overshoots MAXJOBS.
#
# AHADIC.  "Singlet_Sorter ... failed to decompose particle list into singlet"
# returns Return_Value::New_Event (SHERPA/SoftPhysics/Singlet_Sorter.C): the
# event IS discarded and regenerated, its trials carried to the next event
# (SHERPA/Single_Events/Event_Handler.C), so it shows up as "New events: From
# Hadronization: Ahadic" and lowers sum(W)/sum(NTrials) by the discarded
# weight fraction.  Counted per job by `ahadic`.
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
BENCH_REPO=${BENCH_REPO:-$(cd "$HERE/.." && pwd)}
export BENCH_REPO
. "$BENCH_REPO/config.sh"
# THE NEUTRON SET IS LOCAL (data/pdfs/lhapdf, tools/make_neutron_pdf.py).
# Without this every neutron point dies with "PDF ... does not exist" --
# which is how the first pass of tools/sherpa_faser_ladder.sh lost them all.
export LHAPDF_DATA_PATH=$BENCH_REPO/data/pdfs/lhapdf:$LHAPDF_DATA_PATH

SHERPA_BIN=$SHERPA_INSTALL/bin/Sherpa
PY=${BENCH_PYTHON:-python3}
MAXJOBS=${MAXJOBS:-5}
# At most this many INTEGRATIONS at once, so one slot is always left for the
# minutes-long generation jobs and grid reuses instead of all five going to
# hour-long integrations while finished grids wait (seen 2026-09-13).
INTEG_MAX=${INTEG_MAX:-$((MAXJOBS - 1))}
CURRENTS=${CURRENTS:-"nu mu"}
SHOWER=${SHOWER:-CSS}
case "$SHOWER" in
  CSS)  SHOWER_SUFFIX="";      SHOWER_ARGS=() ;;
  Dire) SHOWER_SUFFIX="_Dire"; SHOWER_ARGS=("SHOWER_GENERATOR: Dire")
        ENERGIES=${ENERGIES:-1000} ;;
  *) echo "SHOWER must be CSS or Dire (DIM has no MC@NLO interface)" >&2; exit 1 ;;
esac
DISK_FLOOR_GB=${DISK_FLOOR_GB:-155}
NEV_PER_JOB=25000
JOB_MB=320                   # reserve per running generation job (~8 kB/event)
[ -x "$SHERPA_BIN" ] || { echo "no Sherpa at $SHERPA_BIN" >&2; exit 1; }
[ -x "$SHERPA_NPATCH/bin/Sherpa" ] && [ -f "$SHERPA_NPATCH/NPATCH_STAMP" ] || {
    echo "no patched Sherpa copy at $SHERPA_NPATCH -- run tools/build_sherpa_npatch.sh" >&2; exit 1; }
[ -f "$BENCH_REPO/data/pdfs/lhapdf/NNPDF40_nnlo_as_01180_n/NNPDF40_nnlo_as_01180_n.info" ] || {
    echo "the neutron PDF set is missing -- run tools/make_neutron_pdf.py" >&2; exit 1; }
ENERGIES=${ENERGIES:-$("$PY" -c "import sys; sys.path.insert(0, '$BENCH_REPO/analysis'); import beams; print(' '.join('%g' % e for e in beams.BENCH_ENERGIES))")}

stamp () { date '+%Y-%m-%d %H:%M:%S'; }
say () { echo "[$(stamp)] $*"; }

base_of () {                      # <mu|nu> -> V2 run-dir stem
  if [ "$1" = mu ]; then echo V2_MuonDIS_NLO; else echo V2_NuDIS_NLO; fi
}
template_of () {                  # <mu|nu> -> the template dir whose Process/ is copied
  if [ "$1" = mu ]; then echo MuonDIS_NLO; else echo NuDIS_NLO_ckm3; fi
}
name_of () {                      # <mu|nu> <p|n> <E> -> run-dir name
  echo "$(card_name_of "$1" "$2" "$3")$SHOWER_SUFFIX"
}
card_name_of () {                 # the CSS run-dir name, whose committed card every shower uses
  "$PY" "$BENCH_REPO/analysis/beams.py" name "$(base_of "$1")_$2" "$3"
}
njobs_of () {                     # <E> -> number of 25k jobs
  if [ "$1" = 1000 ]; then echo 8; else echo 2; fi
}
seed_of () {                      # <p|n> <i>
  if [ "$1" = p ]; then echo $((1234 + $2)); else echo $((5234 + $2)); fi
}

# ---------------------------------------------------------------- set-up
setup_dir () {                    # <cur> <run-dir name>
  local cur=$1 name=$2
  local d=$SHERPA_RUNS/$name card=$BENCH_REPO/sherpa/Runs/${name%"$SHOWER_SUFFIX"}/Sherpa.yaml
  [ -f "$card" ] || { echo "no committed card $card -- run tools/make_sherpa_cards.py" >&2; return 1; }
  mkdir -p "$d"
  if [ -e "$d/Sherpa.yaml" ] && [ ! -L "$d/Sherpa.yaml" ]; then
      echo "$d/Sherpa.yaml is a real file, not the repo link -- refusing" >&2; return 1; fi
  ln -sfn "$card" "$d/Sherpa.yaml"
  local seed=$SHERPA_RUNS/$(base_of "$cur")_p
  if [ "$d" = "$seed" ]; then
      if [ ! -d "$d/Process" ]; then
          cp -R "$SHERPA_RUNS/$(template_of "$cur")/Process" "$d/Process"
          say "copied the $(template_of "$cur") process libraries into $name"
      fi
  else
      mkdir -p "$seed"
      [ -d "$seed/Process" ] || cp -R "$SHERPA_RUNS/$(template_of "$cur")/Process" "$seed/Process"
      [ -e "$d/Process" ] || ln -s "$seed/Process" "$d/Process"
  fi
}

# ------------------------------------------------------------------ state
is_neutron () {                   # <run dir or job dir>
  case "$1" in *_NLO_n|*_NLO_n/*|*_NLO_n_*|*_NLO_nbeam|*_NLO_nbeam/*) return 0 ;; esac
  return 1
}
beam_of () {                      # <path> -> lepton PDG code
  case "$1" in *MuonDIS*) echo 13 ;; *) echo 14 ;; esac
}
log_complete () {                 # <integ.log>: BOTH MC@NLO pieces and a finished run
  sed 's/\x1b\[[0-9;]*m//g' "$1" | grep -q "(BVI) : .* pb +-" || return 1
  sed 's/\x1b\[[0-9;]*m//g' "$1" | grep -q "(RS) : .* pb +-" || return 1
  grep -q "^Time: " "$1"
}
bvi_rs () {                       # <integ.log> -> "BVI RS"
  sed 's/\x1b\[[0-9;]*m//g' "$1" | sed -nE 's/.*\((BVI|RS)\) : ([-0-9.e+]+) pb.*/\1 \2/p' \
      | awk '{v[$1]=$2} END {print v["BVI"], v["RS"]}'
}
integ_done () {                   # <dir>
  local d=$1
  [ -s "$d/Results.zip" ] && [ -s "$d/integ.log" ] || return 1
  log_complete "$d/integ.log" || return 1
  # a neutron dir is done only when its integration ran on the 2112 beam
  if is_neutron "$d"; then grep -q "Beam 2: n " "$d/integ.log" || return 1; fi
  return 0
}
job_done () {                     # <jobdir>
  local j=$1
  [ -s "$j/evtfull" ] && [ -s "$j/sherpa.log" ] || return 1
  grep -q "Generated events: $NEV_PER_JOB\$" "$j/sherpa.log" || return 1
  grep -q "^Time: " "$j/sherpa.log" || return 1
  if is_neutron "$j"; then
      [ -e "$j/LIBCHECK_OK" ] || return 1
      grep -q "^OK" "$j/remnant_check.txt" 2>/dev/null || return 1
  fi
  return 0
}

# ------------------------------------------------------- running Sherpa
# One entry point for every Sherpa process: the patched copy in a neutron dir,
# the shared install otherwise.  Foreground; call it from a background subshell.
sherpa_in () {                    # <workdir> <log> <Sherpa args...>
  local w=$1 log=$2 bg
  shift 2
  if is_neutron "$w"; then
      rm -f "$w/LIBCHECK_OK" "$w/LIBCHECK_FAILED"
      ( cd "$w" \
        && export SHERPA_LIBRARY_PATH="$SHERPA_NPATCH/lib/SHERPA-MC/" \
                  SHERPA_SHARE_PATH="$SHERPA_NPATCH/share/SHERPA-MC/" \
        && bench_run "$SHERPA_NPATCH/bin/Sherpa" "$@" > "$log" 2>&1 ) &
      bg=$!
      libcheck "$w" "$bg"
      wait "$bg" || true
  else
      ( cd "$w" && bench_run "$SHERPA_BIN" "$@" > "$log" 2>&1 ) || true
  fi
}

# Which libRemnants did the running process ACTUALLY map?  DYLD_* variables
# would be stripped by caffeinate (SIP), and a copy whose rpaths still named
# the shared install would load the unpatched library without a word -- so
# this looks at the process, not at the configuration.
libcheck () {                     # <workdir> <background pid>
  local w=$1 bg=$2 pid="" k=0 f=$1/mapped_libs.txt want
  want=$SHERPA_NPATCH/lib/SHERPA-MC/libRemnants.0.0.0.dylib
  : > "$f"
  while [ "$k" -lt 300 ]; do
      kill -0 "$bg" 2>/dev/null || break
      pid=$(lsof -a -d cwd -c Sherpa -Fpn 2>/dev/null \
            | awk -v d="$w" '/^p/ {p = substr($0, 2)} /^n/ {if (substr($0, 2) == d) print p}' | head -1)
      if [ -n "$pid" ]; then
          lsof -p "$pid" -Fn 2>/dev/null | sed -n 's/^n//p' | grep '\.dylib$' | sort -u > "$f"
          grep -q '/libRemnants\.0\.0\.0\.dylib$' "$f" && break
      fi
      sleep 1; k=$((k + 1))
  done
  if grep -qx "$want" "$f" && ! grep -q "^$SHERPA_INSTALL/" "$f"; then
      echo "pid $pid mapped $want (md5 $(md5 -q "$want")); $(wc -l < "$f" | tr -d ' ') dylibs, none from $SHERPA_INSTALL" > "$w/LIBCHECK_OK"
  elif ! kill -0 "$bg" 2>/dev/null && [ ! -s "$f" ]; then
      echo "process ended before its libraries could be listed" > "$w/LIBCHECK_FAILED"
  else
      echo "WRONG LIBRARIES (see mapped_libs.txt) -- killing pid $pid" > "$w/LIBCHECK_FAILED"
      [ -n "$pid" ] && kill -TERM "$pid" 2>/dev/null
  fi
}

# --------------------------------------------------------------- actions
integrate () {                    # <dir> (runs in a background subshell)
  local d=$1 old new
  if is_neutron "$d" && [ -s "$d/integ.log" ] && ! grep -q "Beam 2: n " "$d/integ.log"; then
      if [ -s "$d/Results.zip" ] && grep -q "Beam 2: P+" "$d/integ.log" && log_complete "$d/integ.log"; then
          # REUSE the proton-beam + neutron-PDF grid on the 2112 card
          mv "$d/integ.log" "$d/integ_pbeam_npdf.log"
          sherpa_in "$d" integ.log -e 0
          old=$(bvi_rs "$d/integ_pbeam_npdf.log"); new=$(bvi_rs "$d/integ.log")
          if grep -q "Beam 2: n " "$d/integ.log" && log_complete "$d/integ.log" \
             && ! grep -q "Starting the calculation" "$d/integ.log" \
             && awk -v a="$old" -v b="$new" 'BEGIN {split(a, x, " "); split(b, y, " ");
                  for (i = 1; i <= 2; i++) { r = (x[i] - y[i]) / x[i]; if (r < 0) r = -r;
                  if (r > 1e-5 || x[i] == "" || y[i] == "") exit 1 } }'; then
              echo "reused $(date '+%F %T'): proton-beam+_n grid, BVI RS $old -> $new" > "$d/RESULTS_REUSED"
              say "reused the proton-beam grid in $(basename "$d"): BVI RS $old -> $new"
          else
              say "REUSE REFUSED in $(basename "$d") ($old -> $new) -- integrating afresh"
              mv "$d/integ.log" "$d/integ_reuse_refused.log"
              rm -rf "$d/Results.zip" "$d/Results.zip~"
          fi
      else
          say "clearing the partial proton-beam integration in $(basename "$d")"
          rm -rf "$d/Results.zip" "$d/Results.zip~" "$d/integ.log" "$d"/Status__* \
                 "$d/References.tex" "$d/Settings_Report"
      fi
  fi
  integ_done "$d" || sherpa_in "$d" integ.log -e 0 "${SHOWER_ARGS[@]}"
  if ! integ_done "$d"; then
      touch "$d/INTEG_FAILED"
      say "INTEGRATION FAILED: $(basename "$d") -- see $d/integ.log"; return 1; fi
  # RULE 2: the massless-PS convention must have reached the shower.
  grep -q "Massive PS flavours for Comix: (none)" "$d/integ.log" || {
      touch "$d/INTEG_FAILED"
      say "MASSIVE-PS TRAP: $(basename "$d") does not report '(none)'"; return 1; }
  say "integrated $(basename "$d"): $(sed 's/\x1b\[[0-9;]*m//g' "$d/integ.log" \
      | grep -E '\((BVI|RS)\) : ' | sed -E 's/^.*\((BVI|RS)\) : ([^ ]+ pb) \+- \( ([^ ]+ pb).*/\1 \2 +- \3/' | tr '\n' ' ')"
}

generate () {                     # <dir> <i> <seed> (background subshell)
  local d=$1 i=$2 seed=$3
  local j=$d/job_$i
  mkdir -p "$j"
  ln -sfn ../Sherpa.yaml "$j/Sherpa.yaml"
  [ -e "$j/Process" ] || ln -s ../Process "$j/Process"
  cp -f "$d/Results.zip" "$j/Results.zip"
  rm -f "$j/evtfull" "$j/remnant_check.txt" "$j/GEN_FAILED"
  sherpa_in "$j" sherpa.log -e "$NEV_PER_JOB" "RANDOM_SEED: $seed" \
      'EVENT_OUTPUT: ["HepMC3_GenEvent[evtfull]"]' "${SHOWER_ARGS[@]}"
  if [ -s "$j/evtfull" ]; then
      local tgt=p; is_neutron "$j" && tgt=n
      "$PY" "$BENCH_REPO/tools/sherpa_check_events.py" "$j/evtfull" \
          --target "$tgt" --beam "$(beam_of "$j")" > "$j/remnant_check.txt" 2>&1 || true
  fi
  if job_done "$j"; then
      say "generated $(basename "$d")/job_$i (seed $seed): $(ahadic_line "$j"); $(head -1 "$j/remnant_check.txt" | cut -d: -f1)$(is_neutron "$j" && echo ", libcheck OK")"
  else
      touch "$j/GEN_FAILED"
      say "GENERATION FAILED: $(basename "$d")/job_$i -- see $j/sherpa.log"; return 1
  fi
}

ahadic_line () {                  # <jobdir>
  # THE PRINTED Singlet_Sorter MESSAGES ARE CAPPED AT 20 PER JOB ("last
  # allowed error message from 'operator()'"), so their count is a floor,
  # not a rate.  The rate is Sherpa's own New_Event counter for the
  # hadronisation phase, which counts every discarded event.
  local j=$1 ss newev
  ss=$(grep -c "Singlet_Sorter::operator failed to decompose" "$j/sherpa.log" 2>/dev/null || true)
  newev=$(grep -E 'From "Hadronization: Ahadic"' "$j/sherpa.log" 2>/dev/null \
          | sed -E 's/.*: ([0-9]+) \(([0-9]+)\).*/\1 of \2/' | tail -1)
  echo "Ahadic New_Event ${newev:-0} (Singlet_Sorter messages ${ss:-0}, printing capped at 20)"
}

disk_ok () {                      # <running generation jobs>
  local avail_kb need_kb
  avail_kb=$(df -Pk "${PHYSICS24:-$HOME}" | awk 'NR==2 {print $4}')
  need_kb=$(( ($1 + 1) * JOB_MB * 1024 ))
  [ $((avail_kb - need_kb)) -ge $((DISK_FLOOR_GB * 1024 * 1024)) ]
}

# Working directories of every running Sherpa (the caffeinate wrapper is not
# matched: -c Sherpa is the command name).
busy_dirs () { lsof -a -d cwd -c Sherpa -Fn 2>/dev/null | sed -n 's/^n//p'; }
busy () { busy_dirs | grep -qx "$1"; }
running_integ () { busy_dirs | grep "^$SHERPA_RUNS/V2" | grep -vc "/job_[0-9]*$" || true; }
reuse_candidate () {              # <dir>: a finished proton-beam grid in a neutron dir
  is_neutron "$1" && [ -s "$1/Results.zip" ] && [ -s "$1/integ.log" ] \
      && grep -q "Beam 2: P+" "$1/integ.log" && log_complete "$1/integ.log"
}
running () {
  local a b
  a=$(jobs -pr | wc -l | tr -d ' ')
  b=$(busy_dirs | grep -c "^$SHERPA_RUNS/V2" || true)
  if [ "$a" -gt "$b" ]; then echo "$a"; else echo "$b"; fi
}

# ----------------------------------------------------------------- driver
# One scheduler, one slot pool.  Integrations are queued first (they are the
# long pole, ~40 min each) and a point's generation jobs become eligible the
# moment its own integration has finished.  Bash 3.2: the started-set is a
# space-delimited string, not an associative array.
run () {
  local targets=${1:-"p n"} started="" pending d name cur tgt E i n seed gen_running
  say "Sherpa production: currents [$CURRENTS] targets [$targets] energies [$ENERGIES], MAXJOBS=$MAXJOBS (integrations <= $INTEG_MAX), disk floor ${DISK_FLOOR_GB} GB"
  df -h "${PHYSICS24:-$HOME}" | tail -1
  for cur in $CURRENTS; do for tgt in $targets; do for E in $ENERGIES; do
      setup_dir "$cur" "$(name_of "$cur" "$tgt" "$E")"
  done; done; done
  while :; do
    pending=0
    for E in 1000 $ENERGIES; do for cur in $CURRENTS; do for tgt in $targets; do
      case " $ENERGIES " in *" $E "*) ;; *) continue ;; esac
      name=$(name_of "$cur" "$tgt" "$E"); d=$SHERPA_RUNS/$name
      [ -e "$d/INTEG_FAILED" ] && continue
      if ! integ_done "$d"; then
          case "$started" in *" I:$name "*) pending=1; continue ;; esac
          pending=1
          busy "$d" && continue
          [ "$(running)" -lt "$MAXJOBS" ] || continue
          if ! reuse_candidate "$d"; then
              [ "$(running_integ)" -lt "$INTEG_MAX" ] || continue
          fi
          say "integrating $name"
          integrate "$d" &
          started="$started I:$name "
          continue
      fi
      n=$(njobs_of "$E")
      for i in $(seq 1 "$n"); do
          job_done "$d/job_$i" && continue
          [ -e "$d/job_$i/GEN_FAILED" ] && continue
          case "$started" in *" G:$name:$i "*) pending=1; continue ;; esac
          pending=1
          busy "$d/job_$i" && continue
          [ "$(running)" -lt "$MAXJOBS" ] || continue
          gen_running=$(running)
          if ! disk_ok "$gen_running"; then
              say "STOP: starting $name/job_$i would leave < ${DISK_FLOOR_GB} GB free (rule 1b)"
              wait; say "stopped on the disk floor; re-invoke after pruning"; return 1
          fi
          seed=$(seed_of "$tgt" "$i")
          generate "$d" "$i" "$seed" &
          started="$started G:$name:$i "
      done
    done; done; done
    [ "$pending" = 0 ] && [ "$(running)" = 0 ] && break
    sleep 30
  done
  wait
  say "Sherpa production: nothing left to do"
  status
}

check () {
  local arm d
  say "neutron-beam validation: V2check_NuDIS_NLO_{nbeam,pbeam_npdf}"
  for arm in nbeam pbeam_npdf; do
      setup_dir nu "V2check_NuDIS_NLO_$arm"
  done
  for arm in nbeam pbeam_npdf; do
      d=$SHERPA_RUNS/V2check_NuDIS_NLO_$arm
      if integ_done "$d"; then continue; fi
      say "integrating V2check_NuDIS_NLO_$arm"
      integrate "$d" &
  done
  wait
  # a few hundred showered events per arm, for the remnant check
  for arm in nbeam pbeam_npdf; do
      d=$SHERPA_RUNS/V2check_NuDIS_NLO_$arm
      integ_done "$d" || continue
      [ -s "$d/events/evtfull" ] && continue
      mkdir -p "$d/events"
      ln -sfn ../Sherpa.yaml "$d/events/Sherpa.yaml"
      [ -e "$d/events/Process" ] || ln -s ../Process "$d/events/Process"
      cp -f "$d/Results.zip" "$d/events/"
      sherpa_in "$d/events" sherpa.log -e 500 "RANDOM_SEED: 999" \
          'EVENT_OUTPUT: ["HepMC3_GenEvent[evtfull]"]' &
  done
  wait
  say "validation arms done"
}

status () {
  local cur tgt E name d n i ok
  for cur in $CURRENTS; do for tgt in p n; do for E in $ENERGIES; do
      name=$(name_of "$cur" "$tgt" "$E"); d=$SHERPA_RUNS/$name
      [ -d "$d" ] || { printf '  %-28s not set up\n' "$name"; continue; }
      n=$(njobs_of "$E"); ok=0
      for i in $(seq 1 "$n"); do job_done "$d/job_$i" && ok=$((ok + 1)); done
      if integ_done "$d"; then
          printf '  %-28s integrated, %d/%d jobs\n' "$name" "$ok" "$n"
      elif [ -e "$d/INTEG_FAILED" ]; then
          printf '  %-28s INTEGRATION FAILED\n' "$name"
      else
          printf '  %-28s not integrated\n' "$name"
      fi
  done; done; done
}

ahadic () {
  local j
  for j in "$SHERPA_RUNS"/V2_*_NLO_*/job_*; do
      [ -f "$j/sherpa.log" ] || continue
      printf '  %-40s %s\n' "${j#$SHERPA_RUNS/}" "$(ahadic_line "$j")"
  done
}

case "${1:-}" in
  run)    shift; run "${1:-p n}" ;;
  check)  check ;;
  status) status ;;
  ahadic) ahadic ;;
  *) sed -n '2,12p' "$0"; exit 1 ;;
esac
